/** The only state this portal accepts enrollments for. */
export const FIXED_STATE = "Tamil Nadu" as const;

/** Revenue districts of Tamil Nadu. */
export const TAMIL_NADU_DISTRICTS = [
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kanchipuram",
  "Kanyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
] as const;

export const PHOTO_BUCKET = "member-photos";
export const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
/** Profile photo: JPG/JPEG and PNG only (QA BUG-002). */
export const ALLOWED_PHOTO_TYPES = ["image/jpeg", "image/png"];
export const ALLOWED_PHOTO_EXTENSIONS = ["jpg", "jpeg", "png"];

/**
 * BUG-008: assembly constituencies (thogudhi) per revenue district, so the
 * enrollment form can offer linked dropdowns — a district/constituency
 * mismatch becomes impossible and nothing can be misspelled.
 *
 * Compiled from the Delimitation Order 2008 list (234 ACs) mapped onto the
 * current 38 revenue districts. Keys MUST match TAMIL_NADU_DISTRICTS exactly.
 * NOTE: QA's official spelling corrections (BUG-005, pending) should be
 * applied here — this file is the single source of truth for both lists.
 */
export const TAMIL_NADU_CONSTITUENCIES: Record<string, readonly string[]> = {
  Ariyalur: ["Ariyalur", "Jayankondam"],
  Chengalpattu: [
    "Alandur",
    "Chengalpattu",
    "Cheyyur",
    "Madurantakam",
    "Pallavaram",
    "Sholinganallur",
    "Tambaram",
    "Thiruporur",
  ],
  Chennai: [
    "Anna Nagar",
    "Chepauk-Thiruvallikeni",
    "Dr. Radhakrishnan Nagar",
    "Egmore",
    "Harbour",
    "Kolathur",
    "Mylapore",
    "Perambur",
    "Royapuram",
    "Saidapet",
    "Thiru-Vi-Ka-Nagar",
    "Thiruvottiyur",
    "Thiyagarayanagar",
    "Thousand Lights",
    "Velachery",
    "Villivakkam",
    "Virugampakkam",
  ],
  Coimbatore: [
    "Coimbatore (North)",
    "Coimbatore (South)",
    "Kavundampalayam",
    "Kinathukadavu",
    "Mettupalayam",
    "Pollachi",
    "Singanallur",
    "Sulur",
    "Thondamuthur",
    "Valparai",
  ],
  Cuddalore: [
    "Bhuvanagiri",
    "Chidambaram",
    "Cuddalore",
    "Kattumannarkoil",
    "Kurinjipadi",
    "Neyveli",
    "Panruti",
    "Tittakudi",
    "Virudhachalam",
  ],
  Dharmapuri: ["Dharmapuri", "Harur", "Palacode", "Pappireddippatti", "Pennagaram"],
  Dindigul: [
    "Athoor",
    "Dindigul",
    "Natham",
    "Nilakottai",
    "Oddanchatram",
    "Palani",
    "Vedasandur",
  ],
  Erode: [
    "Anthiyur",
    "Bhavanisagar",
    "Bhavani",
    "Erode (East)",
    "Erode (West)",
    "Gobichettipalayam",
    "Modakkurichi",
    "Perundurai",
  ],
  Kallakurichi: ["Kallakurichi", "Rishivandiyam", "Sankarapuram", "Tirukkoyilur", "Ulundurpettai"],
  Kanchipuram: ["Kancheepuram", "Sriperumbudur", "Uthiramerur"],
  Kanyakumari: ["Colachal", "Kanniyakumari", "Killiyoor", "Nagercoil", "Padmanabhapuram", "Vilavancode"],
  Karur: ["Aravakurichi", "Karur", "Krishnarayapuram", "Kulithalai"],
  Krishnagiri: ["Bargur", "Hosur", "Krishnagiri", "Thalli", "Uthangarai", "Veppanahalli"],
  Madurai: [
    "Madurai Central",
    "Madurai East",
    "Madurai North",
    "Madurai South",
    "Madurai West",
    "Melur",
    "Sholavandan",
    "Thirumangalam",
    "Thiruparankundram",
    "Usilampatti",
  ],
  Mayiladuthurai: ["Mayiladuthurai", "Poompuhar", "Sirkazhi"],
  Nagapattinam: ["Kilvelur", "Nagapattinam", "Vedaranyam"],
  Namakkal: [
    "Kumarapalayam",
    "Namakkal",
    "Paramathi Velur",
    "Rasipuram",
    "Senthamangalam",
    "Tiruchengodu",
  ],
  Nilgiris: ["Coonoor", "Gudalur", "Udhagamandalam"],
  Perambalur: ["Kunnam", "Perambalur"],
  Pudukkottai: [
    "Alangudi",
    "Aranthangi",
    "Gandarvakottai",
    "Pudukkottai",
    "Thirumayam",
    "Viralimalai",
  ],
  Ramanathapuram: ["Mudhukulathur", "Paramakudi", "Ramanathapuram", "Tiruvadanai"],
  Ranipet: ["Arakkonam", "Arcot", "Ranipet", "Sholingur"],
  Salem: [
    "Attur",
    "Edappadi",
    "Gangavalli",
    "Mettur",
    "Omalur",
    "Salem (North)",
    "Salem (South)",
    "Salem (West)",
    "Sankari",
    "Veerapandi",
    "Yercaud",
  ],
  Sivaganga: ["Karaikudi", "Manamadurai", "Sivaganga", "Tiruppattur"],
  Tenkasi: ["Alangulam", "Kadayanallur", "Sankarankovil", "Tenkasi", "Vasudevanallur"],
  Thanjavur: [
    "Kumbakonam",
    "Orathanadu",
    "Papanasam",
    "Pattukkottai",
    "Peravurani",
    "Thanjavur",
    "Thiruvidaimarudur",
    "Thiruvaiyaru",
  ],
  Theni: ["Andipatti", "Bodinayakanur", "Cumbum", "Periyakulam"],
  Thoothukudi: [
    "Kovilpatti",
    "Ottapidaram",
    "Srivaikuntam",
    "Thoothukkudi",
    "Tiruchendur",
    "Vilathikulam",
  ],
  Tiruchirappalli: [
    "Lalgudi",
    "Manachanallur",
    "Manapparai",
    "Musiri",
    "Srirangam",
    "Thiruchirappalli (East)",
    "Thiruchirappalli (West)",
    "Thiruverumbur",
    "Thuraiyur",
  ],
  Tirunelveli: ["Ambasamudram", "Nanguneri", "Palayamkottai", "Radhapuram", "Tirunelveli"],
  Tirupathur: ["Ambur", "Jolarpet", "Tiruppattur", "Vaniyambadi"],
  Tiruppur: [
    "Avanashi",
    "Dharapuram",
    "Kangayam",
    "Madathukulam",
    "Palladam",
    "Tiruppur (North)",
    "Tiruppur (South)",
    "Udumalaipettai",
  ],
  Tiruvallur: [
    "Ambattur",
    "Avadi",
    "Gummidipoondi",
    "Madavaram",
    "Maduravoyal",
    "Ponamallee",
    "Ponneri",
    "Thiruvallur",
    "Tiruttani",
  ],
  Tiruvannamalai: [
    "Arani",
    "Chengam",
    "Cheyyar",
    "Kalasapakkam",
    "Kilpennathur",
    "Polur",
    "Tiruvannamalai",
    "Vandavasi",
  ],
  Tiruvarur: ["Mannargudi", "Nannilam", "Thiruvarur", "Thiruthuraipoondi"],
  Vellore: ["Anaikattu", "Gudiyatham", "Katpadi", "Kilvaithinankuppam", "Vellore"],
  Viluppuram: ["Gingee", "Mailam", "Tindivanam", "Vanur", "Vikravandi", "Villupuram"],
  Virudhunagar: [
    "Aruppukkottai",
    "Rajapalayam",
    "Sattur",
    "Sivakasi",
    "Srivilliputhur",
    "Tiruchuli",
    "Virudhunagar",
  ],
};
